[nrf noup] boot: zephyr: use asn1parse.c from TF-PSA-Crypto when PSA
With the outdated copied source file we would get
`asn1parse.c:20:10: fatal error: common.h: No such file or directory`
and anyway it's bad practice to do this.

Update the path to use the original file directly as is, and
also make some adjustments to the Kconfig options that select
CONFIG_MBEDTLS_ASN1_PARSE_C.
Select it in all cases because it's needed to make the needed functions
available in the build.

Signed-off-by: Tomi Fontanilles <tomi.fontanilles@nordicsemi.no>