[nrf noup] mcuboot: use %c constant modifier
Use %c constant modifier to ensure the right value is used.

This fixes the following error seen when compiling with clang:
> error: unknown token in expression

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>